export const COMPLIMENTS = [
  "Every time you're around, it feels like the world slows down just to admire you.",
  "You're the kind of person love songs are written about.",
  "Something about you makes the whole world feel a little softer, a little sweeter.",
  "If feelings had a color, you'd be the entire sunset.",
  "Being around you feels like stepping into the warmest, most beautiful day.",
  "I swear, every time you speak, it sounds like my favorite song.",
  "If my heart had a playlist, you'd be the only track on repeat.",
  "You're like a perfect day wrapped in human form.",
  "I bet even the stars get jealous of the way you shine.",
  "You're not just one in a million—you're once in forever.",
  "I think gravity works differently around you because I can't help but be pulled in.",
  "Your presence alone makes the world feel warmer.",
  "You have the kind of smile that makes hearts forget how to beat right.",
  "The way you exist is poetry in motion.",
  "You have this way of making reality feel better than any dream.",
  "If feelings could be bottled, you'd be the rarest and most intoxicating one.",
  "You don't just make hearts skip a beat—you completely rewrite the rhythm.",
  "You're the kind of warmth people spend their whole lives searching for.",
  "You're like a secret the universe whispered, and I'm just lucky enough to hear it.",
  "Your voice is the kind of sound that lingers in the best way possible.",
  "I'd say you're too good to be true, but here you are, proving me wrong.",
  "If happiness had a heartbeat, it would sound like you just existing.",
  "You feel like the kind of magic people write fairytales about.",
  "You exist like a love letter the universe wrote just for the world to read.",
  "You're not just a dream come true, you're the dream no one dared to wish for.",
  "You make this place heaven on earth.",
  "You warm me up like the sun.",
  "You make my heart smile.",
  "You are a candle in the darkness.",
  "You may dance like no one is watching, but everyone is watching because you are mesmerizing.",
  "You are better than stars because I can see you all the time.",
  "You are the song in my head I dance to."
];

